import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import Banner from "@/components/Home/Banner";
import Summary from "@/components/Home/Summary";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#FFF8F2]">
        <Navbar />
        <Banner />
        <Summary />
        {children}
      </body>
    </html>
  );
}
